//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitExternalAccessClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitExternalAccessClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create wall result.
        /// </summary>
        internal static string CreateWallResult {
            get {
                return ResourceManager.GetString("CreateWallResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create walls.
        /// </summary>
        internal static string CreateWalls {
            get {
                return ResourceManager.GetString("CreateWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get project file path.
        /// </summary>
        internal static string GetProjectFilePath {
            get {
                return ResourceManager.GetString("GetProjectFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key when Revit has started...
        /// </summary>
        internal static string PressAnyKeyWhenRevitHasStarted {
            get {
                return ResourceManager.GetString("PressAnyKeyWhenRevitHasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select command:.
        /// </summary>
        internal static string SelectCommand {
            get {
                return ResourceManager.GetString("SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walls created....
        /// </summary>
        internal static string WallsCreated {
            get {
                return ResourceManager.GetString("WallsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !!!Wrong command!!!.
        /// </summary>
        internal static string WrongCommand {
            get {
                return ResourceManager.GetString("WrongCommand", resourceCulture);
            }
        }
    }
}
