//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitExternalAccessDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitExternalAccessDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while executing the OnIdling event.
        /// </summary>
        internal static string AnErrorOccuredWhileExecutingTheOnIdlingEvent {
            get {
                return ResourceManager.GetString("AnErrorOccuredWhileExecutingTheOnIdlingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start WCF service.
        /// </summary>
        internal static string CouldNotStartWCFService {
            get {
                return ResourceManager.GetString("CouldNotStartWCFService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create wall.
        /// </summary>
        internal static string CreateWall {
            get {
                return ResourceManager.GetString("CreateWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End execute task.
        /// </summary>
        internal static string EndExecuteTask {
            get {
                return ResourceManager.GetString("EndExecuteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish task.
        /// </summary>
        internal static string FinishTask {
            get {
                return ResourceManager.GetString("FinishTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push task to the container.
        /// </summary>
        internal static string PushTaskToTheContainer {
            get {
                return ResourceManager.GetString("PushTaskToTheContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start execute task.
        /// </summary>
        internal static string StartExecuteTask {
            get {
                return ResourceManager.GetString("StartExecuteTask", resourceCulture);
            }
        }
    }
}
